# Trade requests

### Login with the registered user
# @name login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/x-www-form-urlencoded

username=john_doe&password=theStrongP^s$w@rd

###
@authToken = {{login.response.body.$.access_token}}

### Get all trades
GET http://localhost:8080/api/v1/trades
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Put a trade
POST http://localhost:8080/api/v1/trades
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"action": "buy",
	"amount": 10,
	"price": 150.00,
	"symbol": "AAPL"
}